title = "Kirsten Ruge: Infrastructure Person"
baseURL = "https://reinainblood.github.io"
languageCode = "en-us"
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true


[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "A little more about me"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"

[[params.ananke_socials]]
name = "linkedin"
url = "https://www.linkedin.com/in/kruge"
